# Generated by Django 3.2 on 2021-04-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_production',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.car')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.customer')),
            ],
        ),
    ]
